version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "4000:4000"
    networks:
      - mern-app
  api-server:
    image: api-server
    ports:
      - "3000:3000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  data-volume:
  node-modules:
  web-root:
    driver: local
